/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_md;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Maxwell
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    
    private int[] x,y;
    private String[] pares;
    private final String validos = "0123456789";
    private final Random gera = new Random();
    private int linha=1;
    
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        ent.setEditable(false);
        sai.setEditable(false);
        ent.setText("\t                    Entrada:");
        sai.setText("\t                      Saída:");
        tprim.grabFocus();
    }
    public boolean validaCampo(JTextField prim, JTextField ult, JTextField elem){
        int primeiro,ultimo,elemento;
        if(prim.getText().isEmpty()||ult.getText().isEmpty()||elem.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campos vazios. Preencha-os!","Atenção!",JOptionPane.ERROR_MESSAGE);
            tprim.grabFocus();            
            return false;
        }else{
            primeiro=Integer.parseInt(prim.getText());
            ultimo=Integer.parseInt(ult.getText());
            elemento=Integer.parseInt(elem.getText());
            if((primeiro>100)||(ultimo>100)){
                JOptionPane.showMessageDialog(null,"Elementos fora do intervalo. (0 <= m,n <= 100).",
                        "Atenção!",JOptionPane.ERROR_MESSAGE);
                tprim.grabFocus();
                return false;
            }else
                if((elemento<1)||(elemento>10000)){
                    JOptionPane.showMessageDialog(null,"O Número de elementos deve estar entre: 1 e 10000.",
                            "Atenção!",JOptionPane.ERROR_MESSAGE);
                    telem.grabFocus();
                    return false;
                }else
                    if(elemento>Math.pow((ultimo-primeiro)+1,2)){
                        JOptionPane.showMessageDialog(null,"É impossivel gerar pares num valor maior "
                                +"que "+(Math.pow((ultimo-primeiro)+1,2))+"!",
                                "Atenção!",JOptionPane.ERROR_MESSAGE);
                        return false;
                    }else
                        if(primeiro>ultimo){
                            JOptionPane.showMessageDialog(null,"O ultimo elemento deve ser menor que o primeiro.","Atenção!",
                                    JOptionPane.ERROR_MESSAGE);
                            return false;
                        }else
                            return true;
        }
    }
    public void geraConjunto(int m,int n,int r){
        int val = (int)(Math.pow((m-n)+1,2));
        x = new int[r];
        y = new int[r];
        pares = new String[r];
        String[] parEscolhido = new String[r]; // pega apenas os PARES escolhidos, sendo que todos ja foram gerados (x e y).
        int[] posicao = new int[r];
        for(int i=0;i<val;i++)
            for(int j=0;j<val;j++){
                x[i]=i;
                y[i]=j;
                pares[j]="("+x[i]+", "+y[i]+")"; 
                //insere_txt(pares[j]);
            }   
        for(int i=0;i<r;i++){
            parEscolhido[i]=pares[gera.nextInt(r)];
        }
    }
    public boolean verifyCondicao(String[] par, int nPares,int[] x,int[] y){
        boolean verifica = false;
        for(int i=0;i<nPares;i++)
            for(int j=0;j<nPares;j++)
                if((par[i].equals("("+y[j]+", "+x[j]+")"))||(x[j]==y[j]))
                    verifica = true;
        return verifica;
    }
    public boolean filtro(String[] pares,String par,int r){
        boolean verifica = true;
        for(int i=0;i<r;i++){
            for(int j=0;j<r;j++){
                if(par.equals(pares[j]))
                    verifica=false;  
            }
        }
        return verifica;
    }
    public void insere_txt(String texto){
        if(ent.getText().isEmpty()){
            ent.setText(linha+". "+texto);
            linha++;
        }else{
            ent.setText(ent.getText()+"\n"+linha+". "+texto);
            linha++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tprim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tult = new javax.swing.JTextField();
        geraConj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ent = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        sai = new javax.swing.JTextArea();
        limpa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de M.D. por Maxwell Couto, Alice Albuquerque, Luis Filipe & Ana Flávia");
        setUndecorated(true);

        jLabel1.setText("Primeiro elemento do conjunto:");

        tprim.setToolTipText("Primeiro elemento do conjunto.");
        tprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprimActionPerformed(evt);
            }
        });
        tprim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tprimKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tprimKeyTyped(evt);
            }
        });

        jLabel2.setText("Último elemento do conjunto:");

        tult.setToolTipText("Ultimo elemento do conjunto.");
        tult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tultKeyTyped(evt);
            }
        });

        geraConj.setText("Gerar Conjunto");
        geraConj.setToolTipText("Gera aleatoriamente os pares do conjunto.");
        geraConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraConjActionPerformed(evt);
            }
        });

        jLabel3.setText("Nº de pares:");

        telem.setToolTipText("Número de pares do conjunto.");
        telem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telemKeyTyped(evt);
            }
        });

        ent.setColumns(20);
        ent.setRows(5);
        jScrollPane1.setViewportView(ent);

        sai.setColumns(20);
        sai.setRows(5);
        jScrollPane2.setViewportView(sai);

        limpa.setText("Limpar");
        limpa.setToolTipText("Limpar todos os campos.");
        limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setToolTipText("Sair.");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tprim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(geraConj, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(telem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpa))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tprim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geraConj))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(telem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(limpa)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tprimActionPerformed

    private void tprimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprimKeyPressed
       
    }//GEN-LAST:event_tprimKeyPressed

    private void tprimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tprimKeyTyped
        if(!validos.contains(evt.getKeyChar()+""))
            evt.consume();
    }//GEN-LAST:event_tprimKeyTyped

    private void tultKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tultKeyTyped
        if(!validos.contains(evt.getKeyChar()+""))
            evt.consume();
    }//GEN-LAST:event_tultKeyTyped

    private void geraConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraConjActionPerformed
        if(validaCampo(tprim, tult, telem)){
            geraConjunto(Integer.parseInt(tprim.getText()),Integer.parseInt(tult.getText()),
                    Integer.parseInt(telem.getText()));
            geraConj.setEnabled(false);
        }
    }//GEN-LAST:event_geraConjActionPerformed

    private void telemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telemKeyTyped
        if(!validos.contains(evt.getKeyChar()+""))
            evt.consume();
    }//GEN-LAST:event_telemKeyTyped

    private void limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaActionPerformed
        ent.setText("\t                    Entrada:");
        sai.setText("\t                      Saída:");
        tprim.setText(null);
        tult.setText(null);
        telem.setText(null);
        linha=1;
        tprim.grabFocus();
        geraConj.setEnabled(true);
    }//GEN-LAST:event_limpaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ent;
    private javax.swing.JButton geraConj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpa;
    private javax.swing.JTextArea sai;
    private javax.swing.JTextField telem;
    private javax.swing.JTextField tprim;
    private javax.swing.JTextField tult;
    // End of variables declaration//GEN-END:variables
}
